version: '3'

tasks:
  dev:
    desc: "Start development servers for all apps"
    deps:
      - dev:backend
      - dev:frontend
  
  dev:backend:
    desc: "Start the backend development server"
    dir: apps/backend
    env:
      GO_ENV: development
      PORT: 3000
    cmds:
      - go run main.go
  
  dev:frontend:
    desc: "Start the frontend development server"
    dir: apps/frontend
    cmds:
      - pnpm run dev

  clean:
    desc: "Clean all build artifacts"